object Versions {
    const val kotlin = "1.9.22"
    const val coroutines = "1.7.3"
    const val serialization = "1.6.2"
    const val datetime = "0.5.0"
    const val ktor = "2.3.7"
    const val koin = "3.5.3"
    const val koinKmp = "1.1.2"
    const val sqlDelight = "2.0.1"
    const val sqlCipher = "4.5.4"
    const val mongoDriver = "4.11.1"
    const val jwt = "4.4.0"
    const val logback = "1.4.14"
    const val junit = "4.13.2"
    const val kotlinTest = "1.9.22"
    const val mockk = "1.13.9"
}

object Dependencies {
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.serialization}"
    const val datetime = "org.jetbrains.kotlinx:kotlinx-datetime:${Versions.datetime}"
    const val ktorServerCore = "io.ktor:ktor-server-core:${Versions.ktor}"
    const val ktorServerNetty = "io.ktor:ktor-server-netty:${Versions.ktor}"
    const val ktorServerContentNegotiation = "io.ktor:ktor-server-content-negotiation:${Versions.ktor}"
    const val ktorServerAuth = "io.ktor:ktor-server-auth:${Versions.ktor}"
    const val ktorServerAuthJwt = "io.ktor:ktor-server-auth-jwt:${Versions.ktor}"
    const val ktorServerCallLogging = "io.ktor:ktor-server-call-logging:${Versions.ktor}"
    const val ktorServerCors = "io.ktor:ktor-server-cors:${Versions.ktor}"
    const val ktorServerStatusPages = "io.ktor:ktor-server-status-pages:${Versions.ktor}"
    const val ktorServerRateLimit = "io.ktor:ktor-server-rate-limit:${Versions.ktor}"
    const val ktorSerializationJson = "io.ktor:ktor-serialization-kotlinx-json:${Versions.ktor}"
    const val ktorClientCore = "io.ktor:ktor-client-core:${Versions.ktor}"
    const val ktorClientDarwin = "io.ktor:ktor-client-darwin:${Versions.ktor}"
    const val ktorClientAndroid = "io.ktor:ktor-client-android:${Versions.ktor}"
    const val ktorClientContentNegotiation = "io.ktor:ktor-client-content-negotiation:${Versions.ktor}"
    const val ktorClientLogging = "io.ktor:ktor-client-logging:${Versions.ktor}"
    const val koinCore = "io.insert-koin:koin-core:${Versions.koin}"
    const val koinKtor = "io.insert-koin:koin-ktor:${Versions.koin}"
    const val koinLogger = "io.insert-koin:koin-logger-slf4j:${Versions.koin}"
    const val sqlDelightRuntime = "app.cash.sqldelight:runtime:${Versions.sqlDelight}"
    const val sqlDelightCoroutinesExt = "app.cash.sqldelight:coroutines-extensions:${Versions.sqlDelight}"
    const val sqlDelightAndroidDriver = "app.cash.sqldelight:android-driver:${Versions.sqlDelight}"
    const val sqlDelightNativeDriver = "app.cash.sqldelight:native-driver:${Versions.sqlDelight}"
    const val sqlCipherAndroid = "net.zetetic:android-database-sqlcipher:${Versions.sqlCipher}"
    const val mongoDriverSync = "org.mongodb:mongodb-driver-sync:${Versions.mongoDriver}"
    const val mongoDriverKotlin = "org.mongodb:mongodb-driver-kotlin-coroutine:${Versions.mongoDriver}"
    const val jwtAuth = "com.auth0:java-jwt:${Versions.jwt}"
    const val logback = "ch.qos.logback:logback-classic:${Versions.logback}"
    const val junit = "junit:junit:${Versions.junit}"
    const val kotlinTest = "org.jetbrains.kotlin:kotlin-test:${Versions.kotlinTest}"
    const val kotlinTestJunit = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlinTest}"
    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutines}"
    const val ktorServerTests = "io.ktor:ktor-server-tests:${Versions.ktor}"
}
